language: node_js
node_js:
- 5.10.1
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  ssh_known_hosts: 45.55.35.212
before_install:
- chmod 600 ~/.ssh/config
- chmod 600 deploy-diig-key
- mv deploy-diig-key ~/.ssh/id_rsa
- rm deploy-diig-key.enc
- echo -e "Host 45.55.35.212" >> ~/.ssh/config
- echo -e "IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
- cat ~/.ssh/id_rsa
- cat ~/.ssh/known_hosts
- bash scripts/install.sh
before_script:
- bash scripts/install.sh
- npm install grunt-cli -g
script:
- bash scripts/build.sh
after_success:
- bash scripts/deploy.sh
branches:
  only:
  - master
